<?php
use Drupal\Component\Utility\Xss;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Template\url;
use Drupal\Core\Template\ur;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\file\Plugin\Core\Entity\FileInterface;



/**
 * Implements hook_preprocess_menu().
 */
function yg_car_care_preprocess_paragraph(&$variables){
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();
  $variables['title'] = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());

  $variables['#cache']['contexts'][] = 'url';
}
function yg_car_care_preprocess_menu(&$variables, $hook) {
  if ($hook == 'menu__main') { // We're doing that for main menu.
    // Get the current path.
    $current_path = \Drupal::request()->getRequestUri();
    $items = $variables['items'];
    foreach ($items as $key => $item) {
      // If path is current_path, set active to li.
      if ($item['url']->toString() == $current_path) {
        // Add active link.
        $variables['items'][$key]['attributes']['class'] = 'active';
      }
    }
  }
}
function yg_car_care_form_comment_form_alter(&$form, &$form_state, $form_id) {
 $form['form_title'] = array(
  '#markup' => '<h3 class="blog-form-title wow fadeInUp" data-wow-delay="0.2s">Post Comment</h3>',
  );
}
function yg_car_care_preprocess_breadcrumb(&$variables){
  $request = \Drupal::request();
 $route_match = \Drupal::routeMatch();
 $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());

 $variables['breadcrumb'][] = array(
   'text' => $page_title
 );
 $variables['#cache']['contexts'][] = 'url.path';
}

function yg_car_care_preprocess_html(&$variables) {
  $variables['logo_url'] = theme_get_setting('logo.url');
}
function yg_car_care_preprocess_page(&$variables) {
  $variables['basepath'] = $GLOBALS['base_url'];
  $variables['opening_hours_title'] = theme_get_setting('opening_hours_title'); 
  $variables['opening_hours'] = theme_get_setting('opening_hours'); 
  $variables['helpline_title'] = theme_get_setting('helpline_title'); 
  $variables['helpline'] = theme_get_setting('helpline'); 
  $variables['facebook'] = theme_get_setting('facebook');   
  $variables['twitter'] = theme_get_setting('twitter');
  $variables['instagram'] = theme_get_setting('instagram');
  $variables['youtube'] = theme_get_setting('youtube');  
  $variables['contact'] = theme_get_setting('contact'); 
  $variables['contact_desc'] = theme_get_setting('contact_desc'); 
  $variables['phone'] = theme_get_setting('phone'); 
  $variables['email'] = theme_get_setting('email');  

  $bg_image_url = array();
  $path = array();
  $fid = theme_get_setting('bg-image' , 'yg_car_care')[0];
  for ($i = 1; $i <= $fid; $i++) {
  if (!empty($fid)) {
      $file = file_load($fid);
      $uri = $file->url();
      $path = file_create_url($uri);
    }
  }
  $variables['bg_image_url'] = $path;

  $footer_bg_url = array();
  $path = array();
  $fid = theme_get_setting('footer_bg' , 'yg_car_care')[0];
  for ($i = 1; $i <= $fid; $i++) {
  if (!empty($fid)) {
      $file = file_load($fid);
      $uri = $file->url();
      $path = file_create_url($uri);
    }
  }
  $variables['footer_bg_url'] = $path;

}

function yg_car_care_form_system_theme_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id = NULL) {
  // Work-around for a core bug affecting admin themes. See issue #943212.
  


 $form['yg_news_settings']['footer'] = array(
    '#type' => 'details',
    '#title' => t('Theme Settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form ['yg_news_settings']['footer']['opening_hours_title'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Opening Hours Title'),
    '#default_value' => theme_get_setting('opening_hours_title'),
    '#description'   => t("Place this text in the widget spot on your site."),
  ); 

  $form ['yg_news_settings']['footer']['opening_hours'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Opening Hours'),
    '#default_value' => theme_get_setting('opening_hours'),
    '#description'   => t("Place this text in the widget spot on your site."),
  ); 

   $form ['yg_news_settings']['footer']['helpline_title'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Helpline Title'),
    '#default_value' => theme_get_setting('helpline_title'),
    '#description'   => t("Place this text in the widget spot on your site."),
  ); 

    $form ['yg_news_settings']['footer']['helpline'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Helpline'),
    '#default_value' => theme_get_setting('helpline'),
    '#description'   => t("Place this text in the widget spot on your site."),
  ); 

   $form ['yg_news_settings']['footer']['twitter'] = array(
    '#type'          => 'textfield',
    '#title'         => t('twitter'),
    '#default_value' => theme_get_setting('twitter'),
    '#description'   => t("Place this text in the widget spot on your site."),
  );

  $form ['yg_news_settings']['footer']['facebook'] = array(
    '#type'          => 'textfield',
    '#title'         => t('facebook'),
    '#default_value' => theme_get_setting('facebook'),
    '#description'   => t("Place this text in the widget spot on your site."),
  );

 

  $form ['yg_news_settings']['footer']['instagram'] = array(
    '#type'          => 'textfield',
    '#title'         => t('instagram'),
    '#default_value' => theme_get_setting('instagram'),
    '#description'   => t("Place this text in the widget spot on your site."),
  );


  $form ['yg_news_settings']['footer']['youtube'] = array(
    '#type'          => 'textfield',
    '#title'         => t('youtube'),
    '#default_value' => theme_get_setting('youtube'),
    '#description'   => t("Place this text in the widget spot on your site."),
  );


  $form ['yg_news_settings']['footer']['contact'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Contact'),
    '#default_value' => theme_get_setting('contact'),
    '#description'   => t("Place this text in the widget spot on your site."),
  ); 

  $form ['yg_news_settings']['footer']['contact_desc'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Contact Description'),
    '#default_value' => theme_get_setting('contact_desc'),
    '#description'   => t("Place this text in the widget spot on your site."),
  );

  $form ['yg_news_settings']['footer']['email'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Email'),
    '#default_value' => theme_get_setting('email'),
    '#description'   => t("Place this text in the widget spot on your site."),
  );

  $form ['yg_news_settings']['footer']['phone'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Phone'),
    '#default_value' => theme_get_setting('phone'),
    '#description'   => t("Place this text in the widget spot on your site."),
  );



 $form['banner'] = [
    '#type' => 'details',
    '#title' => t('Background Image '),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  ];
  $form['banner']['bg-image'] = [
    '#type' => 'managed_file',
    '#title'    => t('Background Image'),
    '#default_value' => theme_get_setting('bg-image'),
    '#upload_location' => 'public://',
    '#description' => t('Choose your background image for 404,403 pages'),
  ];

  $form['banner']['footer_bg'] = [
    '#type' => 'managed_file',
    '#title'    => t('Footer bg Image'),
    '#default_value' => theme_get_setting('footer_bg'),
    '#upload_location' => 'public://',
    '#description' => t('Choose your background image for footer'),
  ];

  $form['#submit'][] = 'yg_car_care_form_submit';

  
}

function yg_car_care_form_submit(&$form, $form_state) {
  $fid = $form_state->getValue('bg-image');
  if (array_key_exists(0,$fid)){
    $file = file_load($fid[0]);
    if (!empty($file)) {
      $file->setPermanent();
      $file->save();
      $file_usage = \Drupal::service('file.usage');
      $file_usage->add($file, 'yg_car_care', 'themes', 1);
    }
  }
  $fid = $form_state->getValue('footer_bg');
  if (array_key_exists(0,$fid)){
    $file = file_load($fid[0]);
    if (!empty($file)) {
      $file->setPermanent();
      $file->save();
      $file_usage = \Drupal::service('file.usage');
      $file_usage->add($file, 'yg_car_care', 'themes', 1);
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function yg_car_care_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  // Get Request Object.
  $request = \Drupal::request();

  // If there is HTTP Exception..
  if ($exception = $request->attributes->get('exception')) {
    // Get the status code.
    $status_code = $exception->getStatusCode();
    if (in_array($status_code, array(401, 403, 404))) {
      $suggestions[] = 'page__' . $status_code;
    }
  }
}

function yg_car_care_theme(&$existing, $type, $theme, $path) {
  $hooks = array();
  $hooks['user_login_form'] = array(
      'render element' => 'form',
      'template' => 'user-login-form',
  );
  return $hooks;
}

?>